queue_rules:
  - name: default
    conditions:
      - base=main
      - check-success=build-docs
      - check-success=lint
      - check-success=tests (macos-10.15, 3.8)
      - check-success=tests (macos-10.15, 3.9)
      - check-success=tests (ubuntu-18.04, 3.8)
      - check-success=tests (ubuntu-18.04, 3.10)

pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - base=main
      - author~=^dependabot(|-preview)\[bot\]$
      - check-success=build-docs
      - check-success=lint
      - check-success=tests (macos-10.15, 3.8)
      - check-success=tests (macos-10.15, 3.9)
      - check-success=tests (ubuntu-18.04, 3.8)
      - check-success=tests (ubuntu-18.04, 3.10)
    actions:
      queue:
        name: default
  - name: automatic merge when CI passes, reviewed, and has automerge label
    conditions:
      - and:
        - or:
          - "#approved-reviews-by>=1"
          - author=grahamgower
        - base=main
        - label=automerge
        - check-success=build-docs
        - check-success=lint
        - check-success=tests (macos-10.15, 3.8)
        - check-success=tests (macos-10.15, 3.9)
        - check-success=tests (ubuntu-18.04, 3.8)
        - check-success=tests (ubuntu-18.04, 3.10)
    actions:
      queue:
        name: default
