name: dinf
channels:
  # prioritise conda-forge over defaults channel
  - conda-forge
  - defaults
dependencies:
  # https://docs.anaconda.com/mkl-optimizations/index.html
  - mkl
  - numpy
  # Jax and friends.
  - jax
  - flax
  - optax
  # The rest.
  - arviz
  - demes
  - msprime
  - zarr
  - zeus-mcmc
  - pip
  - pip:
    # No conda packages available.
    - gradient-free-optimizers
