name: dinf
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # https://docs.anaconda.com/mkl-optimizations/index.html
  - mkl
  - numpy
  # Jax and friends.
  - jax
  - flax
  - optax
  # The rest.
  - arviz
  - cyvcf2 >= 0.30.14
  - emcee
  - demes >= 0.2.1
  - msprime >= 1.0.4
