name: dinf
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - numpy
  # Jax and friends.
  - jax
  - flax >= 0.5.2
  - optax
  # The rest.
  - cyvcf2 >= 0.30.14
  - emcee
  - demes >= 0.2.1
  - demesdraw
  - msprime >= 1.0.4
  - matplotlib
  - multiprocess
  - adjustText
