name: tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  canceller:
    runs-on: ubuntu-20.04
    steps:
      - name: cancel previous runs
        uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{ github.token }}

  tests:
    defaults:
      run:
        shell: bash
    timeout-minutes: 20
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, macos-10.15]
        python-version: [3.8]
        include:
          - os: ubuntu-18.04
            python-version: "3.10"
          - os: macos-10.15
            python-version: 3.9
    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python-version }}

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: install dependencies
        run: |
          python -m pip install -r requirements/minimal.txt
          python -m pip install -r requirements/test.txt

      - name: install bcftools
        run: |
          # The tests call "bgzip" and "bcftools".
          if [ "$RUNNER_OS" == "Linux" ]; then
            # Ubuntu keeps bgzip in the tabix package.
            sudo apt-get update
            sudo apt-get install bcftools tabix
          elif [ "$RUNNER_OS" == "macOS" ]; then
            brew update
            brew install bcftools
          else
            echo "Don't know how to install bcftools on $RUNNER_OS"
            exit 1
          fi

      - name: run pytest
        run: |
          python -m pytest \
            -n auto \
            -v \
            --cov=dinf \
            --cov-report=term-missing \
            --cov-report=xml \
            tests

      - name: upload coverage report to codecov
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
          env_vars: OS,PYTHON
